pull_request_title: "✨ feat: new crowdin update"
pull_request_labels:
  - crowdin
  - l10n
commit_message: "✨ feat(%original_file_name%): new translation from Crowdin (%language%)"
append_commit_message: 
files:
  - source: /template/source/**/**
    ignore:
      - /template/%locale_with_underscore%
    translation: /template/%locale_with_underscore%/**/%original_file_name%
