name: Update source & progress
run-name: Updating translation source & progress

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1,13 * * *"

jobs:
  update-source-and-progress:
    if: github.repository == 'harukaxxxx/stable-diffusion-webui-localization-zh_TW'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10.6"

      - name: install python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "./requirements.txt"

      - name: download folder from stable-diffusion-webui-localization-source
        run: |
          mkdir -p temp/source
          curl -sSL https://github.com/harukaxxxx/stable-diffusion-webui-localization-source/archive/refs/heads/main.tar.gz | tar -xz --strip-components=2 -C temp/source stable-diffusion-webui-localization-source-main/source

      - name: copy and overwrite source files
        run: |
          mkdir -p template/source
          cp -rf temp/source/* template/source

      - name: run crowdin tool.py
        env:
          crowdin_api_token: ${{ secrets.CROWDIN_PROGRESS_CHECKER_API_KEY }}
        run: python 'tools/crowdin-tool.py'

      - name: configure git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: commit changes
        run: |
          git add template
          git add README.md
          git diff-index --quiet HEAD || (git commit -a -m "✨ feat: update translation source & progress" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
